---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - create
- apiGroups:
  - kubeforen.org
  resources:
  - checkpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeforen.org
  resources:
  - checkpoints/finalizers
  verbs:
  - update
- apiGroups:
  - kubeforen.org
  resources:
  - checkpoints/status
  verbs:
  - get
  - patch
  - update
